#!/bin/bash

[ -f "/etc/yunohost/yunohost.conf" ] && [ "$(grep dovecot /etc/yunohost/yunohost.conf | cut -d= -f2)" = "no" ] || exit 1

HOSTNAME=$(hostname -f)
TEMPLATE="/usr/share/yunohost/yunohost-config/dovecot"

if [ -f /etc/yunohost/current_host ];
then
  DOMAIN=$(cat /etc/yunohost/current_host)
  find $TEMPLATE -type f -exec sed -i "s/yunohost.org/$DOMAIN/g" {} \;
fi

# Create vmail user
adduser --system --ingroup mail --uid 500 vmail

# Install dovecot main configuration
install -o root -g root -m 0644 $TEMPLATE/{dovecot.conf,dovecot-ldap.conf} /etc/dovecot/
if [ ! -f /proc/net/if_inet6 ];
then
  sed -i 's|^listen.*|listen = \*|' /etc/dovecot/dovecot.conf 
fi

# Setup Sieve
[ -d /etc/dovecot/global_script ] && rm /etc/dovecot/global_script
[ ! -d /etc/dovecot/global_script ] && mkdir -m 0770 /etc/dovecot/global_script
install -o root -g root -m 0755 $TEMPLATE/sa-learn-pipe.sh /usr/bin/sa-learn-pipe.sh
install -o vmail -g mail -m 0660  $TEMPLATE/global_script/dovecot.sieve /etc/dovecot/global_script
sievec /etc/dovecot/global_script/dovecot.sieve
chmod 0660 /etc/dovecot/global_script/dovecot.svbin

# Reload
service dovecot reload > /dev/null 2>&1
