#!/bin/sh

set -e

case "$1" in
	remove|purge)
	[ -f /etc/dovecot/global_script/dovecot.svbin ] && rm /etc/dovecot/global_script/dovecot.svbin
	[ -f /etc/dovecot/dovecot.conf ] && rm /etc/dovecot/dovecot.conf
	[ -f /etc/dovecot/dovecot-ldap.conf ] && rm /etc/dovecot/dovecot-ldap.conf
	;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
